package com.anime.arena.battle;

public enum BattleStep {
    DONE_SLEEPING, STILL_SLEEPING, RECHARGING, CHECK_MOVE_FAIL,DISPLAY_FAILED_MOVE,CHECK_ABILITY_CONTACT, DRAIN_TEXT, RECOIL_TEXT, END_STATE,
    CHECK_MOVE_MESSAGES, MISSED, NO_EFFECT, FIRST_HURT_BURN, FIRST_HURT_POISON, FIRST_BURN, FIRST_POISON, SECOND_POISON, SECOND_BURN, CLAMP, DONE_END_TURN,
    SECOND_HURT_BURN, SECOND_HURT_POISON, UPDATE_WEATHER, DAMAGING_WEATHER, PARALYSIS_CHECK, FAILED_PARALYSIS_CHECK,DONE_SLEEP_STATE,
    FIRST_EFFECT_RAIN, SECOND_EFFECT_RAIN, FIRST_RAIN, SECOND_RAIN, USE_WEATHER,
    FIRST_EFFECT_SUN, SECOND_EFFECT_SUN, FIRST_SUN, SECOND_SUN,
    FIRST_EFFECT_SAND, SECOND_EFFECT_SAND, FIRST_SAND, SECOND_SAND,
    FIRST_EFFECT_HAIL, SECOND_EFFECT_HAIL, FIRST_HAIL, SECOND_HAIL, TEXT_BEFORE_ENEMY_FAINT,
    CONFUSION_CHECK, FAIL_CONFUSION_ROLL, IS_CONFUSED, SNAPPED_OUT_OF_IT, HURT_SELF_IN_CONFUSION, CONFUSION_ANIMATION,
    DISPLAY_EXP_GAINED_TEXT, UPDATE_EXP_BAR, CHECK_NEW_MOVES, EVALUATE_NEW_MOVE_RESULT, LEARN_NEW_MOVE,
    PLAYER_FAINTED, ENEMY_FAINTED, PLAYER_FAINT_TEXT, ENEMY_FAINT_TEXT,
    GET_NEXT_POKEMON;
}
